export const studentData = {
  name: "John Doe",
  email: "john.doe@example.com",
  avatar: "https://picsum.photos/seed/student-avatar/200/200",
  bio: "Passionate learner exploring web development and design.",
  stats: {
    enrolledCourses: 5,
    completedCourses: 2,
    certificates: 2,
    wishlist: 12,
    totalPoints: 1250,
  },
  enrolledCourses: [
    {
      id: 1,
      title: "Complete Web Design: from Figma to Webflow to Freelancing",
      instructor: "Vako Shvili",
      progress: 65,
      totalLessons: 120,
      completedLessons: 78,
      image: "https://picsum.photos/seed/course1/600/400",
      lastAccessed: "2 hours ago",
    },
    {
      id: 2,
      title: "The Ultimate Guide to Game Development with Unity",
      instructor: "Jonathan Weinberger",
      progress: 30,
      totalLessons: 85,
      completedLessons: 25,
      image: "https://picsum.photos/seed/course2/600/400",
      lastAccessed: "1 day ago",
    },
    {
      id: 3,
      title: "Python for Data Science and Machine Learning Bootcamp",
      instructor: "Jose Portilla",
      progress: 10,
      totalLessons: 150,
      completedLessons: 15,
      image: "https://picsum.photos/seed/course3/600/400",
      lastAccessed: "3 days ago",
    },
  ],
  recentActivity: [
    {
      id: 1,
      type: "progress",
      message: "Completed 3 lessons in 'Complete Web Design'",
      time: "2 hours ago",
    },
    {
      id: 2,
      type: "enrollment",
      message: "Enrolled in 'Python for Data Science'",
      time: "3 days ago",
    },
    {
      id: 3,
      type: "quiz",
      message: "Scored 90% in 'CSS Grid Quiz'",
      time: "5 days ago",
    },
  ],
  reviews: [
    {
      id: 1,
      course: "Complete Web Design: from Figma to Webflow to Freelancing",
      rating: 5,
      comment: "This course is amazing! I learned so much about design principles.",
      date: "1 week ago",
    },
    {
      id: 2,
      course: "The Ultimate Guide to Game Development with Unity",
      rating: 4,
      comment: "Great content, but the instructor speaks a bit fast.",
      date: "2 weeks ago",
    },
  ],
  quizAttempts: [
    {
      id: 1,
      quiz: "CSS Grid Quiz",
      course: "Complete Web Design",
      score: 90,
      totalQuestions: 20,
      date: "5 days ago",
      status: "Passed",
    },
    {
      id: 2,
      quiz: "Unity Basics",
      course: "Game Development with Unity",
      score: 75,
      totalQuestions: 15,
      date: "2 weeks ago",
      status: "Passed",
    },
    {
      id: 3,
      quiz: "Python Syntax",
      course: "Python for Data Science",
      score: 45,
      totalQuestions: 10,
      date: "3 weeks ago",
      status: "Failed",
    },
  ],
  orderHistory: [
     {
        id: "ORD-001",
        date: "2023-10-15",
        items: ["Complete Web Design", "Game Development with Unity"],
        total: 24.99,
        status: "Completed",
     },
     {
        id: "ORD-002",
        date: "2023-09-20",
        items: ["Python for Data Science"],
        total: 12.99,
        status: "Completed",
     },
  ],
};

export const instructorData = {
  name: "Jane Smith",
  email: "jane.smith@example.com",
  avatar: "https://picsum.photos/seed/instructor-avatar/200/200",
  bio: "Senior Web Developer and Instructor with 10+ years of experience.",
  stats: {
    totalCourses: 15,
    totalStudents: 1250,
    totalEarnings: 12580,
    averageRating: 4.8,
    totalReviews: 450,
  },
  courses: [
    {
      id: 101,
      title: "Advanced React Patterns",
      students: 450,
      rating: 4.9,
      revenue: 4500,
      status: "Published",
      image: "https://picsum.photos/seed/course101/600/400",
    },
    {
      id: 102,
      title: "Mastering TypeScript",
      students: 300,
      rating: 4.7,
      revenue: 3000,
      status: "Published",
      image: "https://picsum.photos/seed/course102/600/400",
    },
    {
      id: 103,
      title: "GraphQL Zero to Hero",
      students: 120,
      rating: 4.8,
      revenue: 1200,
      status: "Draft",
      image: "https://picsum.photos/seed/course103/600/400",
    },
  ],
  recentSales: [
    {
      id: 1,
      student: "Alice Wonderland",
      course: "Advanced React Patterns",
      amount: 49.99,
      date: "2 hours ago",
    },
    {
      id: 2,
      student: "Bob Builder",
      course: "Mastering TypeScript",
      amount: 39.99,
      date: "5 hours ago",
    },
    {
      id: 3,
      student: "Charlie Chocolate",
      course: "Advanced React Patterns",
      amount: 49.99,
      date: "1 day ago",
    },
  ],
  announcements: [
    {
      id: 1,
      title: "New Course Launched!",
      content: "We have just launched our new course on GraphQL.",
      date: "2 days ago",
      course: "All Students",
    },
    {
      id: 2,
      title: "Maintenance Scheduled",
      content: "The platform will be down for maintenance on Sunday.",
      date: "1 week ago",
      course: "All Students",
    },
  ],
  assignments: [
    {
        id: 1,
        title: "React Component Composition",
        course: "Advanced React Patterns",
        dueDate: "2023-11-15",
        submissions: 45,
    },
    {
        id: 2,
        title: "TypeScript Generics",
        course: "Mastering TypeScript",
        dueDate: "2023-11-20",
        submissions: 20,
    },
  ],
};

export const instructorsList = [
  {
    id: 1,
    name: "Rolands Granger",
    role: "Developer",
    image: "https://picsum.photos/seed/rolands/300/300",
    rating: 4.9,
    reviews: 200,
    coursesCount: 12,
    duration: "169hr 20min",
    studentsCount: 50,
    bio: "I am a web developer with a vast array of knowledge in many different front end and back end languages, responsive frameworks, databases, and best code practices.",
    tags: ["Web Design", "Development", "Re-Design"],
  },
  {
    id: 2,
    name: "Lisa Lopezer",
    role: "Finance",
    image: "https://picsum.photos/seed/lisa/300/300",
    rating: 4.4,
    reviews: 130,
    coursesCount: 22,
    duration: "15hr 06min",
    studentsCount: 22,
    bio: "I am a web developer with a vast array of knowledge in many different front end....",
    tags: ["Accounting", "Commerce"],
  },
  {
    id: 3,
    name: "Charles Ruizer",
    role: "Designer",
    image: "https://picsum.photos/seed/charles/300/300",
    rating: 4.6,
    reviews: 50,
    coursesCount: 8,
    duration: "45hr 30min",
    studentsCount: 150,
    bio: "Creative designer with over 10 years of experience in UI/UX design.",
    tags: ["UI Design", "UX Design"],
  },
  {
    id: 4,
    name: "Emily Clark",
    role: "Marketing Head",
    image: "https://picsum.photos/seed/emily/300/300",
    rating: 4.8,
    reviews: 95,
    coursesCount: 15,
    duration: "80hr 15min",
    studentsCount: 300,
    bio: "Expert in digital marketing and SEO strategies.",
    tags: ["Marketing", "SEO"],
  },
  {
    id: 5,
    name: "John Smith",
    role: "Data Scientist",
    image: "https://picsum.photos/seed/john/300/300",
    rating: 4.7,
    reviews: 120,
    coursesCount: 10,
    duration: "120hr 45min",
    studentsCount: 200,
    bio: "Data scientist with a passion for teaching machine learning.",
    tags: ["Data Science", "Python"],
  },
];

export const courseCategories = [
    {
      id: 1,
      title: "Graphic Design",
      image: "https://picsum.photos/seed/design/400/300",
      lessons: 45,
    },
    {
      id: 2,
      title: "Photography",
      image: "https://picsum.photos/seed/photography/400/300",
      lessons: 13,
    },
    {
      id: 3,
      title: "Medical Terminology",
      image: "https://picsum.photos/seed/medical/400/300",
      lessons: 21,
    },
    {
      id: 4,
      title: "UX/UI Design",
      image: "https://picsum.photos/seed/uxui/400/300",
      lessons: 14,
    },
    {
      id: 5,
      title: "Web Development",
      image: "https://picsum.photos/seed/webdev/400/300",
      lessons: 50,
    },
    {
      id: 6,
      title: "Digital Marketing",
      image: "https://picsum.photos/seed/marketing/400/300",
      lessons: 32,
    },
    {
      id: 7,
      title: "Data Science",
      image: "https://picsum.photos/seed/datascience/400/300",
      lessons: 40,
    },
    {
      id: 8,
      title: "Business Analytics",
      image: "https://picsum.photos/seed/business/400/300",
      lessons: 18,
    },
];

export const blogPosts = [
  {
    id: 1,
    title: "The Future of Web Development: 2024 Trends",
    excerpt: "Explore the emerging technologies and frameworks that are shaping the future of the web.",
    content: `
      <p>Web development is an ever-evolving field, and keeping up with the latest trends is crucial for any developer. In 2024, we are seeing a massive shift towards more performance-oriented frameworks and the integration of AI into development workflows.</p>
      
      <h2>1. AI-Driven Development</h2>
      <p>Artificial Intelligence is no longer just a buzzword. Tools like GitHub Copilot and ChatGPT are becoming integral parts of the coding process, helping developers write cleaner code faster.</p>

      <h2>2. Server Components</h2>
      <p>React Server Components are changing how we build modern web applications, offering better performance by reducing the amount of JavaScript sent to the client.</p>

      <h2>3. The Rise of Edge Computing</h2>
      <p>Edge computing is bringing computation closer to the data source, improving response times and bandwidth usage.</p>
    `,
    author: "John Doe",
    date: "October 15, 2023",
    image: "https://picsum.photos/seed/blog1/600/400",
    category: "Technology",
    readTime: "5 min read",
    tags: ["Web Development", "AI", "Trends"],
  },
  {
    id: 2,
    title: "Mastering UI/UX Design Principles",
    excerpt: "A comprehensive guide to creating user-friendly and aesthetically pleasing interfaces.",
    content: "...",
    author: "Jane Smith",
    date: "October 10, 2023",
    image: "https://picsum.photos/seed/blog2/600/800",
    category: "Design",
    readTime: "7 min read",
    tags: ["UI/UX", "Design", "Guide"],
  },
  {
    id: 3,
    title: "Top 10 Programming Languages to Learn",
    excerpt: "Discover the most in-demand programming languages that can boost your career.",
    content: "...",
    author: "Mike Johnson",
    date: "September 28, 2023",
    image: "https://picsum.photos/seed/blog3/600/500",
    category: "Career",
    readTime: "6 min read",
    tags: ["Programming", "Career", "Languages"],
  },
  {
    id: 4,
    title: "The Importance of Soft Skills for Developers",
    excerpt: "Why technical skills alone are not enough to succeed in the tech industry.",
    content: "...",
    author: "Sarah Williams",
    date: "September 15, 2023",
    image: "https://picsum.photos/seed/blog4/600/400",
    category: "Career",
    readTime: "4 min read",
    tags: ["Soft Skills", "Communication", "Teamwork"],
  },
  {
    id: 5,
    title: "Understanding Blockchain Technology",
    excerpt: "A beginner-friendly introduction to the decentralized world of blockchain.",
    content: "...",
    author: "David Brown",
    date: "August 30, 2023",
    image: "https://picsum.photos/seed/blog5/600/600",
    category: "Technology",
    readTime: "8 min read",
    tags: ["Blockchain", "Crypto", "Decentralization"],
  },
  {
    id: 6,
    title: "Effective Time Management Strategies",
    excerpt: "Tips and tricks to stay productive and manage your time effectively as a remote worker.",
    content: "...",
    author: "Emily Davis",
    date: "August 12, 2023",
    image: "https://picsum.photos/seed/blog6/600/500",
    category: "Productivity",
    readTime: "5 min read",
    tags: ["Productivity", "Time Management", "Remote Work"],
  },
];

export const blogComments = [
  {
    id: 1,
    blogId: 1,
    author: "Alice Wonderland",
    avatar: "https://picsum.photos/seed/alice/100/100",
    date: "October 16, 2023",
    content: "Great article! I'm really excited about Server Components.",
  },
  {
    id: 2,
    blogId: 1,
    author: "Bob Builder",
    avatar: "https://picsum.photos/seed/bob/100/100",
    date: "October 17, 2023",
    content: "AI in development is a game changer for sure. Productivity has skyrocketed.",
  },
  {
    id: 3,
    blogId: 2,
    author: "Charlie Design",
    avatar: "https://picsum.photos/seed/charlie/100/100",
    date: "October 11, 2023",
    content: "Thanks for the tips on UI/UX. Very helpful for beginners.",
  },
  {
    id: 4,
    blogId: 3,
    author: "Dave Developer",
    avatar: "https://picsum.photos/seed/dave/100/100",
    date: "September 29, 2023",
    content: "I think Rust should be on this list too!",
  },
  {
    id: 5,
    blogId: 3,
    author: "Eve Engineer",
    avatar: "https://picsum.photos/seed/eve/100/100",
    date: "September 30, 2023",
    content: "Python is definitely #1 for data science.",
  },
  {
    id: 6,
    blogId: 4,
    author: "Frank Founder",
    avatar: "https://picsum.photos/seed/frank/100/100",
    date: "September 16, 2023",
    content: "Soft skills are underrated. Crucial for leadership.",
  },
  {
    id: 7,
    blogId: 5,
    author: "Grace G",
    avatar: "https://picsum.photos/seed/grace/100/100",
    date: "August 31, 2023",
    content: "Blockchain is complex but this article explains it well.",
  },
  {
    id: 8,
    blogId: 6,
    author: "Hank Hero",
    avatar: "https://picsum.photos/seed/hank/100/100",
    date: "August 13, 2023",
    content: "Pomodoro technique changed my life!",
  },
];
